# Site settings
baseurl = "https://blog.vdka.me/"
languageCode = "en-us"
title = "Ethan Jackwitz"
theme = "hemingway2"

[params]

[params.highlight]
style = "github"
languages = ["go", "swift"]

[[params.social]]
url = "https://github.com/vdka"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/ejackwitz"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
