# Site settings
baseurl = "https://blog.vdka.com/"
languageCode = "en-us"
title = "Ethan Jackwitz"
# Define how many pages appear per site
paginate = 10
canonifyurls = true
theme = "hugo-cactus-theme"
googleAnalytics = "UA-65631355-2"
# disqusShortname = "blog-ejackwitz"
# pygmentsUseClasses = true
# PygmentsCodeFences = true
# PygmentsStyle = "friendly"

[params]
    name = "Ethan Jackwitz"
    description = "A website about iOS Development."
    bio = "Brisbane based iOS Developer."
    # Enter optionally your twitter account
    twitter = "ejackwitz"
    enableRSS = true

    profileImage = "img/reuleauxTriangle.svg"

    # The variables below are optionally too and can be used to
    # translate or customize each string of the theme.

    # Navigation links
    home = "Home"
    about = ""
    subscribe = ""
    # Pagination links
    olderPosts = ""
    newerPosts = ""
    readMore = ""
    copyright = ""
    # Sharing options and author information in posts
    aboutAuthor = "Brisbane based iOS Developer."
    tweet = ""
    share = ""
    # 404 page
    title404 = ""
    subtitle404 = ""
