baseURL = "https://blog.vdka.me"
languageCode = "en-us"
title = "Ethan Jackwitz"
theme = "minimal"

[params]
    author = "Ethan Jackwitz"
    description = "Personal blog theme powered by Hugo"
    githubUsername = "vdka"
    accent = "white"
    showBorder = true
    backgroundColor = "black"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["c", "go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/notes/"
    name = "Notes"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://github.com/vdka"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/ejackwitz"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/ejackwitz/"
    name = "linkedin"
    weight = 3
